# -*- coding: utf-8 -*-
"""KARAR_AGACI.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DW-CrnG_4rR_7V1OXqjw_QqPDYLFZlJz
"""

#KARAR AGACI

baslangic = input("Lütfen aklinizdan bir elektronik esya tutunuz ve bu asamada sadece Enter'a basiniz!")

Frage1 = input("Bu esya elektronik mi?(Evet oder Hayir").title().strip()

while True:
    if Frage1 == "Evet":
        Frage2 = input("Tek el ile tasinabilir mi?(Evet oder Hayir").title().strip()        
        if Frage2 =="Hayir":
            Frage3 = input("Birseyler izlenebilir mi?(Evet oder Hayir").title().strip()
            if Frage3 == "Evet":
                print("Sectiginiz esya Televizyon!")
                break
            else:
                print("Sectiginiz esya: Camasir makinasi!")
                break
        else:
            Frage4 = input("Sectiginiz esya en az 10 KG agirliga sahip mi?(Evet oder Hayir").title().strip()
            if Frage4 == "Evet":
                print("Sectiginiz esya: Elektrikli Bisiklet!")
                break
            else:
                Frage5 = input("Dokunmatik ekrani var mi?(Evet oder Hayir").title().strip()
                if Frage5 == "Hayir":
                    print("Sectiginiz esya: Kasali PC!")
                    break
                else:
                    Frage6 = input("Ekrani 7'' den kücük mü? ").title().strip()
                    if Frage6 == "Evet":
                        print("Sectiginiz esya: Handy!")
                        break
                    else:
                        if Frage6 == "Hayir":
                            print("Sectiginiz esya: Ipad!")
                        break
    else:
        Frage1 = input("Bu esya elektronik mi?(Evet oder Hayir").title().strip()